### ISSUE TITLE
Lab is not found in Nitrous

### ISSUE THREAD

**Issue by innatewonderer** [learn-co-curriculum/project-euler-even-fibonacci#2]
<img width="1085" alt="nitrous_lab_open_redirect" src="https://cloud.githubusercontent.com/assets/2320322/10872353/fbfb3e08-80cd-11e5-94f8-ec32237aaa0b.png">

**Comment by matbalez-zz** [comment]
Seems Iike an application bug (and not curriculum issue?). Can you raise an
issue on ironboard repo or use Report a Bug link in app?

**Comment by innatewonderer** [comment]
Yes, confirmed that I didn't have that track added. It's working now that it was added.
Closing
